# Generated by Django 5.1.6 on 2025-02-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
