# Generated by Django 5.1.6 on 2025-02-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
